### ISSUE TITLE
Python 3.10 error on clean install

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB_data_preprocess#57]
Installing on python 3.10 on mac produced an error related to a flag used for supressing warnings in a function call. The error appears to be related to a function not supported until Python 3.11 -- we can make a simple change to be backwards compatible. 

### Error trace 

``` bash
python3.10 -m venv ~/pyenv310_clean
source ~/pyenv310_clean/bin/activate
uv pip install ngiab-data-preprocess --prerelease=allow
uv pip install ngiab-data-preprocess --prerelease=allow
python -m ngiab_data_cli -i cat-825550 --subset --start 2010-01-01 --end 2010-01-02 --forcings --realization --run
.
.
.
<Lots of output>
.
.
.
2024-11-15 12:58:30,921 - INFO - Forcing generation complete! Zonal stats computed in 23.705850839614868 seconds
2024-11-15 12:58:30,998 - INFO - Saving to disk
2024-11-15 12:58:30,999 - ERROR - An error occurred: catch_warnings.__init__() got an unexpected keyword argument 'action'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jshalgren/pyenv310_clean/lib/python3.10/site-packages/ngiab_data_cli/__main__.py", line 218, in <module>
    main()
  File "/Users/jshalgren/pyenv310_clean/lib/python3.10/site-packages/ngiab_data_cli/__main__.py", line 131, in main
    create_forcings(
  File "/Users/jshalgren/pyenv310_clean/lib/python3.10/site-packages/data_processing/forcings.py", line 262, in create_forcings
    compute_zonal_stats(gdf, merged_data, forcing_paths.forcings_dir)
  File "/Users/jshalgren/pyenv310_clean/lib/python3.10/site-packages/data_processing/forcings.py", line 190, in compute_zonal_stats
    write_outputs(forcings_dir, variables)
  File "/Users/jshalgren/pyenv310_clean/lib/python3.10/site-packages/data_processing/forcings.py", line 222, in write_outputs
    with warnings.catch_warnings(action="ignore"):
TypeError: catch_warnings.__init__() got an unexpected keyword argument 'action'
(pyenv310_clean) jshalgren@UA-17YDF9D data_processing %
```

### Possible Fix
Exploring the following. Seems to work on 3.10, 3.11, and 3.12. 
``` diff
diff --git a/modules/data_processing/forcings.py b/modules/data_processing/forcings.py
index 4c56183..8f721d2 100644
--- a/modules/data_processing/forcings.py
+++ b/modules/data_processing/forcings.py
@@ -219,7 +219,10 @@ def write_outputs(forcings_dir, variables):
     # add the catchment ids as a 1d data var
     final_ds["ids"] = final_ds["catchment"].astype(str)
     # time needs to be a 2d array of the same time array as unix timestamps for every catchment
-    with warnings.catch_warnings(action="ignore"):
+    with warnings.catch_warnings():
+        warnings.simplefilter("ignore")
         time_array = (
             final_ds.time.astype("datetime64[s]").astype(np.int64).values // 10**9
         )  ## convert from ns to s
```

**Comment by JoshCu** [comment]
fixed! https://github.com/CIROH-UA/NGIAB_data_preprocess/commit/98794f7898cd0a280c8c1078ce214d4bff0e4ed7
included in release v3.0.3
